# Generated by Django 5.2.7 on 2025-11-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='ganadora',
            field=models.BooleanField(default=False, verbose_name='¿Es ganadora?'),
        ),
    ]
