"""
Django settings for proyecto_rifa project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7yl!9x)u17i6c$6@6u5&0_pugc0g+cv+@$^kkt%l203#x6ne2*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

RAILWAY_HOSTNAME = os.environ.get('RAILWAY_STATIC_URL')
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]
if RAILWAY_HOSTNAME:
    ALLOWED_HOSTS.append(RAILWAY_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rifa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto_rifa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_rifa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        conn_max_age=600,
        ssl_require=False # Railway maneja SSL externamente
    )
}
if not DATABASES['default']:
    print("--- USANDO BASE DE DATOS LOCAL (SQLite) ---")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Configuración de archivos estáticos
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static_root'), # Aquí es donde pondremos nuestros archivos CSS, JS, imágenes
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_production')# Para el despliegue en producción

# URL a la que se redirige si un usuario no está logueado
LOGIN_URL = '/cuentas/login/'

# Redirección después de iniciar sesión
LOGIN_REDIRECT_URL = '/mis-boletas/'

# Redirección después de cerrar sesión
LOGOUT_REDIRECT_URL = '/cuentas/login/'

CSRF_TRUSTED_ORIGINS = []
if RAILWAY_HOSTNAME:
    # Railway usa https
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_HOSTNAME}')



JAZZMIN_SETTINGS = {
    # Título de la ventana del navegador
    "site_title": "Admin Rifas Renixir",

    # Título en la barra de login y en la cabecera
    "site_header": "Rifas Renixir",

    # Logo (usa el mismo de tus boletas)
    # Asegúrate que esta ruta sea correcta
    "site_logo": "img/logo_renixir.jpg",

    # Tema (hay muchos, "darkly" se verá bien con tu diseño)
    "theme": "darkly",
    "ui_fluid": True,
    # --- AQUÍ LA MAGIA ---
    # Enlaces en el menú superior
    "topmenu_links": [

        # 1. Enlace para "Volver al Sitio"
        # Apunta a la raíz "/", que redirigirá a "mis-boletas" o "login"
        {"name": "Ir al Sitio Web", "url": "/", "new_window": False},

        # 2. Enlace a tu modelo de Usuarios (útil)
        {"model": "auth.User"},
    ],

    # --- Mejoras visuales ---
    "show_ui_builder": False, # Oculta el personalizador en vivo
    "changeform_format": "horizontal_tabs", # Mejora la vista de "editar"
}